### ISSUE TITLE
Looks similar to what TOTP would need. Common code?

### ISSUE THREAD

**Issue by nealeu** [rwinch/spring-security-webauthn#3]
Hi Rob,

This looks as though it shares some config and patterns as adding TOTP would need.

I'm tempted to fork this and see where I can get to with some tests adding the filter chain into mock MVC.  We might then see if my hunch is right :-)

**Comment by rwinch** [comment]
I don't think that is the case. WebAuthn has more/different parameters than TOTP. Feel free to experiment with it and get back to me, but I suspect that your findings will be that it is a different API
