### ISSUE TITLE
The key of credProtect extension in  AuthenticationExtensionsClientInputs is NOT `credProtect`

### ISSUE THREAD

**Issue by ynojima** [rwinch/spring-security-webauthn#58]
https://github.com/rwinch/spring-security-webauthn/blob/0d1db4c3f9d6f315adcdb1ed35bfc1e588e056c3/spring-security-webauthn/src/main/java/org/springframework/security/webauthn/api/ImmutableAuthenticationExtensionsClientInput.java#L34

It should be noted that the `credProtect` extension, due to a design mistake, contains not a single "credProtect" key, but two keys: "credentialProtectionPolicy" and "enforceCredentialProtectionPolicy".
https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-to-authenticator-protocol-v2.2-rd-20230321.html#sctn-credProtect-extension

Related discussion: https://github.com/w3c/webauthn/issues/1430

**Comment by rwinch** [comment]
Thanks @ynojima ! This is now fixed in in main :smile:
